@baseUrl = http://localhost:3000

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjYwZjQwYjQwYjQ0MjIzYjQ0MjI0ZjciLCJ1c2VybmFtZSI6InNvaGVlbm5lZWViIiwiaWF0IjoxNjI0NjYwNjY4LCJleHAiOjE2MjQ2NjQyNjh9.1

@pharmacyId = 678ea63c01d1a8ee1efe98d1
@userId = 678ea3a10a2274571539d26d

# ### Get all reviews (Admin only)
# GET {{baseUrl}}/pharmacy-reviews
# Authorization: Bearer {{adminToken}}

# ### Get pharmacy reviews
# GET {{baseUrl}}/pharmacy-reviews/pharmacy/{{pharmacyId}}
# Authorization: Bearer {{token}}

# ### Create new review
POST {{baseUrl}}/pharmacy-review
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "pharmacyId": "{{pharmacyId}}",
  "userId": "{{userId}}",
  "rating": 4,
  "comment": "Great service and friendly staff"
}

# ### Update review (Admin only)
# PUT {{baseUrl}}/pharmacy-reviews/{{reviewId}}
# Authorization: Bearer {{adminToken}}
# Content-Type: application/json

# {
#   "isApproved": true
# }

# ### Delete review (Admin only)
# DELETE {{baseUrl}}/pharmacy-reviews/{{reviewId}}
# Authorization: Bearer {{adminToken}}

# ### Report review
# POST {{baseUrl}}/pharmacy-reviews/{{reviewId}}/report
# Authorization: Bearer {{token}}
# Content-Type: application/json

# {
#   "reason": "Inappropriate content"
# }

# ### Approve review (Admin only)
# PUT {{baseUrl}}/pharmacy-reviews/{{reviewId}}/approve
# Authorization: Bearer {{adminToken}}